// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherFavorites.Infrastracture;

namespace WeatherFavorites.Infrastracture.Migrations
{
    [DbContext(typeof(FavoritesContext))]
    [Migration("20210704211759_AddStringKeyMigration")]
    partial class AddStringKeyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            modelBuilder.Entity("WeatherFavorites.Domain.CityFavorite", b =>
                {
                    b.Property<string>("CityKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CityLocalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryLocalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CityKey");

                    b.ToTable("CityFavorite");
                });
#pragma warning restore 612, 618
        }
    }
}
